name: Deploy

on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed

jobs:
  deploy:
    if: (github.event.workflow_run.conclusion == 'success') && (github.event.pull_request.merged)
    name: cd
    runs-on: ubuntu-latest
    steps:
       - id: step1
         run: echo "test=hello"
