name: Build

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo 'v1'
        
  job2: 
     needs: job1
     uses: ./.github/workflows/cd.yml
