name: Build

on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
    types: [ opened, edited, reopened ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello"
        
  job2: 
     needs: job1
     if: (github.event.workflow_run.conclusion == 'success') && (github.event.pull_request.merged)
     uses: ./.github/workflows/cd.yml
