name: Build

on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
    branches:
      - 'main'
      - 'development'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello"
        
  job2: 
     needs: job1
     if: (github.event.pull_request.merged) && (github.ref == 'refs/heads/development')
     uses: ./.github/workflows/cd.yml
