name: Build

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ZS-sarthak/testing 
        ref: main
        
    - name: Run a script
      run: |
        pwd
        ls
        bash ./github/scripts/test.sh
