name: Build

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo 'v1'
        
  # job2: 
  #    needs: job1
  #    steps:
  #     - id: step1
  #       run: echo (github.event.pull_request.merged)
  #     - id: step1
  #       run: echo (github.event.pull_request.merged)
    
  #    run: (github.event.pull_request.merged) && (github.ref == 'refs/heads/main')
  #    uses: ./.github/workflows/cd.yml
